# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'IU_Maps' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
	
  pod 'SwiftyJSON'
  pod 'Google/Analytics'
  pod 'pop'

  # Pods for IU_Maps

end
